-- phpMyAdmin SQL Dump
-- version 3.3.9
-- http://www.phpmyadmin.net
--
-- Servidor: localhost
-- Tempo de Geração: Abr 19, 2016 as 04:41 
-- Versão do Servidor: 5.5.8
-- Versão do PHP: 5.3.5

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Banco de Dados: `banco`
--

-- --------------------------------------------------------

--
-- Estrutura da tabela `tb_dados_conteudo`
--

CREATE TABLE IF NOT EXISTS `tb_dados_conteudo` (
  `cod_numero` int(11) NOT NULL AUTO_INCREMENT,
  `titulo_conteudo` varchar(50) COLLATE utf8_polish_ci NOT NULL,
  `sub_titulo` varchar(50) COLLATE utf8_polish_ci NOT NULL,
  `data_hora` datetime NOT NULL,
  `imagem_img` varchar(100) COLLATE utf8_polish_ci NOT NULL,
  `conteudo` varchar(1500) CHARACTER SET utf8 COLLATE utf8_spanish2_ci NOT NULL,
  `autor_nome` varchar(50) CHARACTER SET utf8 COLLATE utf8_spanish2_ci NOT NULL,
  PRIMARY KEY (`cod_numero`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_polish_ci AUTO_INCREMENT=12 ;

--
-- Extraindo dados da tabela `tb_dados_conteudo`
--

INSERT INTO `tb_dados_conteudo` (`cod_numero`, `titulo_conteudo`, `sub_titulo`, `data_hora`, `imagem_img`, `conteudo`, `autor_nome`) VALUES
(1, 'teste teste', 'html+css', '2016-04-15 00:00:00', '', '*{margin:0; padding:0px;}\r\nbody{\r\n	background-color:black;\r\n}\r\n#pagina_mestra{\r\n	width:800px;\r\n	height:100%; /* para q pagina mestra seja auto ajustavel */\r\n	margin:0px auto;\r\n	background-color:transparent;\r\n}\r\n#banner{\r\n	width:800px;\r\n	height:150px;\r\n	background-color:none;\r\n	background-image:url("../imagens/rascunhofundo-pagina.png");\r\n	border-radius:20px 20px 60px 250px;\r\n	margin:80px 0px 0px;\r\n}\r\n#menu_pricipal{\r\n	width:800px;\r\n	height:60px;\r\n	background-color:#ccc;\r\n	border-radius:20px;\r\n	margin:4px 0px;\r\n}\r\n#corpo_pagina_conteudo{\r\n	width:800px;\r\n	height:auto;\r\n	background-color:trasparent;\r\n	border-radius:10px;\r\n	border-radius:10px;\r\n}\r\n#corpo_pagina_conteudo_conteudo{\r\n	width:800px;\r\n	height:auto;\r\n	background:beige;\r\n	border-radius:10px;\r\n}\r\n#menu_rodape{\r\n	width:800px;\r\n	height:80px;\r\n	background-color:orange;\r\n	border-radius:10px;\r\n	margin:4px 0px;\r\n}\r\n#rodape{\r\n	width:800px;\r\n	height:70px;\r\n	background-color:pink;\r\n	border-radius:10px;\r\n	margin:4px 0px;\r\n}\r\n/* formataÃ§Ã£o dos dados a serem puxados do banco */\r\n#cod_numero{\r\n	text-align:center;\r\n	width:60px;\r\n	height:40px;\r\n	background-color:black;\r\n	float:left;\r\n	margin:5px;\r\n	border-radius:15px;\r\n	border:2px solid black;\r\n	font-size:25px;\r\n	padding-top:5px;\r\n	color:white;\r\n}\r\n#data_hora{\r\n	text-align:center;\r\n	width:200px;\r\n	height:30px;\r\n	background-color:yellow;\r\n	float:right;\r\n	margin:5px;\r\n	border-radius:15px;\r\n	border:2px solid black;\r\n	font-size:20px;\r\n	padding:5px;\r\n}\r\n#div_01{\r\n	height:800px;\r\n	height:50', 'juliano claudio lino'),
(2, 'Exibindo dados em uma tabela PHP/MySql', 'html+css', '0000-00-00 00:00:00', '', '	Para vocÃª entender melhor este post, vocÃª precisa ter uma boa noÃ§Ã£o de â€œcomo fazer consultas em uma tabela do MySQLâ€.\r\nSabendo disso, vamos comeÃ§ar a melhorar a nossa consulta, ordenando de acordo com as colunas, sejam ela de forma\r\ncrescente ou decrescente.\r\n	A nossa sintaxe utilizada juntamente com o SELECT Ã© o â€œORDER BYâ€œ: SELECT nomedascolunas FROM nomedatabel ORDER\r\nBY nomedacoluna ASC/DESC; EntÃ£o vamos aos exemplos. Supondo que eu queira fazer uma consulta numa tabela chamada\r\nâ€œclientesâ€ e quero pegar somente os nomes e nÃºmero de telefones deles, mas que seja ordenado pelo nome de forma\r\ncrescente, ou seja, de A atÃ© Z, devemos executar o seguinte SQL: \r\n1 SELECT nome,telefone FROM `clientes` ORDER BY nome;\r\n	VocÃª deve ter percebido que na sintaxe que eu passei, estou informando logo apÃ³s o nome da coluna para botar ASC\r\nou DESC, mas que nÃ£o botei neste comando de exemplo. Realmente nÃ£o botei pelo simples fato de, por padrÃ£o, o MySQL\r\njÃ¡ realiza a consulta de forma crescente, mas que nÃ£o atrapalha em nada vocÃª acrescentar o ASC no final do comando,\r\nficando assim: \r\n\r\n	1 SELECT nome,telefone FROM `clientes` ORDER BY nome ASC; \r\n	O resultado seria esse:\r\n1 Ana | 1111-1111 \r\n2 AndrÃ© | 3333-3333 \r\n3 AntÃ´nio | 2222-2222 \r\n4 Diego | 4444-4444 \r\n5 Diogo | 5555-5555 \r\n6 JoÃ£o | 8888-8888 \r\n7 JosÃ© | 7777-7777 \r\n8 Maria | 6666-6666 \r\n9 ... \r\n	Caso a gente queira fazer o inverso na ordenaÃ§Ã£o dos dados, ou seja, fazer a consulta de forma decrescent', 'juliano claudio lino'),
(3, 'Estudo de Caso: Hospital Samaritano e a implementa', 'estudo de caso', '0000-00-00 00:00:00', '', 'Gerenciar de forma eficiente processos assistenciais e administrativos, gerar dados relevantes para a tomada de decisÃµes estratÃ©gicas do hospital e aumentar a transparÃªncia das informaÃ§Ãµes geradas na instituiÃ§Ã£o em todos os seus departamentos. Essas sÃ£o algumas das vantagens em se adotar um sistema de ERP clÃ­nico ou administrativo. No entanto, para que isso seja possÃ­vel, Ã© necessÃ¡rio que processos sejam revistos e o hospital tenha um modelo de governanÃ§a em TI adequado para suportar as novas tecnologias. Em 2005, quando o atual gerente de TI do hospital Samaritano, Klaiton SimÃ£o, assumiu sua funÃ§Ã£o na instituiÃ§Ã£o, ele trabalhava com sistemas de gestÃ£o diferentes: um com foco na gestÃ£o assistencial, desenvolvido pelo prÃ³prio hospital, e um administrativo- financeiro, da Microsiga, atual TOTVS. Em 2006 e 2007, o executivo atuou fortemente na mudanÃ§a do entÃ£o atual modelo de governanÃ§a de TI do Samaritano, e em 2008, apÃ³s a reformulaÃ§Ã£o, iniciou o projeto de implantaÃ§Ã£o de uma nova ferramenta de ERP. O projeto de escolha do novo sistema comeÃ§ou em 2008, e o primeiro passo foi constituir um comitÃª gestor do projeto que tivesse o envolvimento de todas as lideranÃ§as da organizaÃ§Ã£o, uma vez que essa iniciativa nÃ£o poderia ser vista apenas como um projeto de TI, e sim como uma demanda corporativa. â€œO Hospital Samaritano, naquele momento, jÃ¡ estava iniciando a construÃ§Ã£o do novo complexo hospitalar, e, por esse motivo, precisÃ¡vamos de uma nova', 'juliano claudio lino'),
(4, 'edrddddd', 'reeeeeeeeeeee', '0000-00-00 00:00:00', '', 'testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes testes te', 'juliano lino'),
(5, 'edrddddd', 'teste teste teste teste ', '0000-00-00 00:00:00', 'http://i.imgur.com/fO3PGgB.jpg', '						', 'juliano claudio lino'),
(6, 'edrddddd', 'teste teste teste teste ', '0000-00-00 00:00:00', 'http://i.imgur.com/fO3PGgB.jpg', '						', 'juliano claudio lino'),
(7, 'Centralizar horizontalmente uma pÃ¡gina na tela:', 'teste teste teste teste ', '0000-00-00 00:00:00', 'http://i.imgur.com/fO3PGgB.jpg', 'teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste ', 'juliano claudio lino'),
(8, 'Centralizar horizontalmente uma pÃ¡gina na tela:', 'teste teste teste teste ', '0000-00-00 00:00:00', 'http://i.imgur.com/fO3PGgB.jpg', 'teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste ', 'juliano claudio lino'),
(9, 'edrddddd', 'teste teste teste teste ', '0000-00-00 00:00:00', 'http://i.imgur.com/lwBiPh0.jpg', 'teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste ', 'juliano claudio lino'),
(10, 'edrddddd', 'teste teste teste teste ', '0000-00-00 00:00:00', 'http://i.imgur.com/lwBiPh0.jpg', 'teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste teste ', 'juliano claudio lino'),
(11, 'teste do dia 18', 'teste de inserÃ§Ã£o de imagens', '0000-00-00 00:00:00', 'http://i.imgur.com/F0WSiKk.jpg', 'Isso Ã© apenas um teste de php/html Isso Ã© apenas um teste de php/html Isso Ã© apenas um teste de php/html Isso Ã© apenas um teste de php/html Isso Ã© apenas um teste de php/html Isso Ã© apenas um teste de php/html Isso Ã© apenas um teste de php/html Isso Ã© apenas um teste de php/html Isso Ã© apenas um teste de php/html Isso Ã© apenas um teste de php/html Isso Ã© apenas um teste de php/html Isso Ã© apenas um teste de php/html Isso Ã© apenas um teste de php/html Isso Ã© apenas um teste de php/html Isso Ã© apenas um teste de php/html Isso Ã© apenas um teste de php/html Isso Ã© apenas um teste de php/html Isso Ã© apenas um teste de php/html Isso Ã© apenas um teste de php/html Isso Ã© apenas um teste de php/html Isso Ã© apenas um teste de php/html Isso Ã© apenas um teste de php/html Isso Ã© apenas um teste de php/html Isso Ã© apenas um teste de php/html Isso Ã© apenas um teste de php/html Isso Ã© apenas um teste de php/html Isso Ã© apenas um teste de php/html Isso Ã© apenas um teste de php/html Isso Ã© apenas um teste de php/html Isso Ã© apenas um teste de php/html Isso Ã© apenas um teste de php/html Isso Ã© apenas um teste de php/html Isso Ã© apenas um teste de php/html Isso Ã© apenas um teste de php/html Isso Ã© apenas um teste de php/html Isso Ã© apenas um teste de php/html Isso Ã© apenas um teste de php/html Isso Ã© apenas um teste de php/html Isso Ã© apenas um teste de php/html Isso Ã© apenas um teste de php/html Isso Ã© apenas um teste de php/html Isso Ã© apenas um teste ', 'juliano claudio lino');
